workflows:
  ios_capacitor_release:
    name: iOS Capacitor Release
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "com.orirot.givit"
        XCODE_PROJECT_PATH: "ios/App"
        XCODE_SCHEME: "App"
      xcode: 16.4
      node: { version: v20.12.2 }
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build
          npx cap sync ios
          cd ios/App && pod install && cd -

      - name: Install signing (manual)
        script: |
          KEYCHAIN_PATH="$HOME/Library/Keychains/codemagic.keychain-db"
          security create-keychain -p "" codemagic.keychain
          security default-keychain -s codemagic.keychain
          security unlock-keychain -p "" codemagic.keychain
          security set-keychain-settings -t 3600 -l codemagic.keychain

          # import certificate
          echo "$P12_BASE64" | base64 --decode > dist.p12
          security import dist.p12 -k codemagic.keychain -P "$P12_PASSWORD" -A

          # install provisioning profile
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "$DIST_PROFILE_BASE64" | base64 --decode > dist.mobileprovision
          UUID=$(grep -a -o "[-A-Z0-9]\\{36\\}" dist.mobileprovision | head -n 1)
          cp dist.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"

      - name: Xcode build & archive
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$UUID" \
            | xcpretty
          cd -

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/export" \
            -allowProvisioningUpdates \
            | xcpretty

      - name: Upload to App Store
        script: |
          IPA_PATH="$(find "$CM_BUILD_DIR/export" -name '*.ipa' -maxdepth 1 | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA found"; exit 1
          fi

          echo "✅ Uploading $IPA_PATH..."
          xcrun iTMSTransporter -m upload \
            -apiKey "$APP_STORE_CONNECT_API_KEY_ID" \
            -apiIssuer "$APP_STORE_CONNECT_ISSUER_ID" \
            -assetFile "$IPA_PATH" -v informational
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
