workflows:
  ios-capacitor-release:
    name: iOS Capacitor Release
    max_build_duration: 60
    environment:
      xcode: latest
      node: 20
      cocoapods: default
      vars:
        WEB_DIR: "dist"                   # אם הפרונט מוציא ל-'build' — שנה כאן
        IOS_WORKSPACE: "ios/App/App.xcworkspace"
        IOS_SCHEME: "App"                 # ברירת המחדל של Capacitor
        BUNDLE_ID: "com.orirot.givit"    # עדכן במידת הצורך
    cache:
      cache_paths:
        - ~/.npm
        - ios/Pods -> ios/Podfile.lock
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build
          test -d "$WEB_DIR" || (echo "Missing $WEB_DIR after build" && exit 1)

      - name: Capacitor sync iOS (uses capacitor.config.ts)
        script: |
          npx cap sync ios
          test -d ios/App || (echo "Missing ios/App after sync" && exit 1)

      - name: Verify bundle id (informational)
        script: |
          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ios/App/App/Info.plist || true
          echo "Expected: $BUNDLE_ID"

      - name: Archive (Release)
        script: |
          set -e
          xcodebuild -workspace "$IOS_WORKSPACE" \
                     -scheme "$IOS_SCHEME" \
                     -configuration Release \
                     -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
                     -allowProvisioningUpdates \
                     clean archive

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>uploadSymbols</key><true/>
            <key>destination</key><string>export</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          PLIST

      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ipa" \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive

    publishing:
      app_store_connect:
        submit_to_testflight: true
        # אם תרצה להוסיף קבוצות בטא ספציפיות:
        # beta_groups:
        #   - Internal Testers
