# codemagic.yaml
workflows:
  ios_capacitor_release:
    name: iOS Capacitor Release
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT_PATH: "ios/App"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.orirot.givit"        # שנה לבאנדל שלך
        APPLE_APP_ID: "1234567890"           # ה-App ID מ-App Store Connect (אופציונלי לפרסום)
        MARKETING_VERSION: "1.0.0"           # גרסה שיווקית, יעדכן ב-build
      flutter: { version: stable }           # לא חובה; יישאר ללא שימוש בפרויקטי Web/Capacitor
      node: { version: v20.12.2 }
      xcode: 16.4
      cocoapods: default
      # --- חתימה אוטומטית דרך App Store Connect API ---
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "$BUNDLE_ID"
        # צריך להוסיף את המפתח תחת App settings > Environment variables כסיקרטים:
        app_store_connect_api_key:
          key_id: Encrypted(APP_STORE_KEY_ID)
          issuer_id: Encrypted(APP_STORE_ISSUER_ID)
          # זהו תוכן ה- .p8 כמחרוזת (Base64 או טקסט גולמי). ב-Codemagic שומרים כסיקרט.
          private_key: Encrypted(APP_STORE_API_PRIVATE_KEY_P8)
    scripts:
      # Node + build
      - name: Install deps
        script: |
          npm ci
      - name: Web build
        script: |
          npm run build
      - name: Capacitor sync iOS
        script: |
          npx cap sync ios
          cd $XCODE_PROJECT_PATH && pod install && cd -

      # גרסה/Build
      - name: Bump build number (agvtool)
        script: |
          cd $XCODE_PROJECT_PATH
          # קובע גרסה שיווקית (CFBundleShortVersionString)
          xcrun agvtool new-marketing-version $MARKETING_VERSION
          # מגדיל build מספרי אוטומטית
          xcrun agvtool next-version -all
          cd -
      # ארכוב עם Xcode
      - name: Xcode archive
        script: |
          ARCHIVE_PATH="$CM_BUILD_DIR/App.xcarchive"
          xcodebuild \
            -workspace "$XCODE_PROJECT_PATH/App.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath "$ARCHIVE_PATH" \
            clean archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$CM_DEVELOPER_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            | xcpretty
      # יצוא IPA (App Store)
      - name: Export IPA
        script: |
          EXPORT_OPTS_PLIST="$CM_BUILD_DIR/ExportOptions.plist"
          cat > "$EXPORT_OPTS_PLIST" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadSymbols</key><true/>
            <key>stripSwiftSymbols</key><true/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTS_PLIST" \
            -exportPath "$CM_BUILD_DIR/export" | xcpretty

          ls -la "$CM_BUILD_DIR/export"

      # העלאה ל-App Store Connect (Transporter דרך Codemagic)
      - name: Upload to App Store Connect
        script: |
          IPA_PATH="$(/usr/bin/find "$CM_BUILD_DIR/export" -name "*.ipa" -maxdepth 1 | head -n1)"
          if [ -z "$IPA_PATH" ]; then
            echo "No IPA found to upload"; exit 1
          fi
          # Codemagic משתמש ב-iTMSTransporter דרך xcrun; עם API key אין צורך ב-verify נפרד.
          xcrun iTMSTransporter -m upload \
            -apiKey "$APP_STORE_KEY_ID" \
            -apiIssuer "$APP_STORE_ISSUER_ID" \
            -assetFile "$IPA_PATH" \
            -v informational || exit 1
    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
