workflows:
  ios_capacitor_release:
    name: iOS Capacitor (Auto signing via ASC API)
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "com.orirot.givit"
        XCODE_PROJECT_PATH: "ios/App"
        XCODE_SCHEME: "App"
        APPLE_TEAM_ID: $APPLE_TEAM_ID
      xcode: 16.4
      node: { version: v20.12.2 }
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "$BUNDLE_ID"
        app_store_connect_api_key:
          key_id: Encrypted(APP_STORE_CONNECT_API_KEY_ID)
          issuer_id: Encrypted(APP_STORE_CONNECT_ISSUER_ID)
          # חשוב: זה צריך להיות תוכן קובץ ה-p8 הגולמי (לא Base64)
          private_key: Encrypted(APP_STORE_CONNECT_API_KEY_P8)
    scripts:
      - name: Install deps & sync
        script: |
          npm ci
          npm run build
          npx cap sync ios
          cd ios/App && pod install && cd -

      - name: Archive (automatic signing)
        script: |
          xcodebuild \
            -workspace "$XCODE_PROJECT_PATH/App.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            clean archive | xcpretty

      - name: Export IPA
        script: |
          EXPORT_OPTS_PLIST="$CM_BUILD_DIR/ExportOptions.plist"
          cat > "$EXPORT_OPTS_PLIST" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>stripSwiftSymbols</key><true/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTS_PLIST" \
            -exportPath "$CM_BUILD_DIR/export" \
            -allowProvisioningUpdates | xcpretty

          ls -la "$CM_BUILD_DIR/export"

      - name: Sanity check (did signing assets install?)
        script: |
          echo "=== Identities ==="
          security find-identity -v -p codesigning || true
          echo "=== Profiles ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa

    publishing:
      app_store_connect:
        # כאן לא חייבים את ה-private key שוב; רק מזהים
        api_key: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
