workflows:
  ios-app-store:
    name: GivIt iOS App Store Deploy
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - o3
      vars:
        BUNDLE_ID: "${o3.BUNDLE_ID}"
        APPLE_TEAM_ID: "${o3.APPLE_TEAM_ID}"
        ASC_ISSUER_ID: "${o3.ASC_ISSUER_ID}"
        ASC_KEY_ID: "${o3.ASC_KEY_ID}"
        APP_SPECIFIC_PASSWORD: "${o3.APP_SPECIFIC_PASSWORD}"
        XCODE_SCHEME: "Runner"  # שנה אם משתמש ב-Scheme אחר
      flutter: 3.24.0  # גרסת Flutter עדכנית, שנה לפי הצורך
    integrations:
      app_store_connect: GivItAPIKey
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --platform IOS \
            --type IOS_APP_STORE \
            --certificate-type IOS_DISTRIBUTION
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: false  # העלאה ידנית, לא אוטומטית
    artifacts:
      - ios/ipa/*.ipa
      - ios/ipa/*.dSYM.zip