workflows:
  ios-app-store:
    name: GivIt iOS App Store Deploy
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        BUNDLE_ID: "com.orirot.givit"
        APPLE_TEAM_ID: "39WVDVZKGE"
        ASC_ISSUER_ID: "cb979aca-72c6-42a9-8a75-6d6cf1fb264e"
        ASC_KEY_ID: "JQ82YP1TDCU0"
        APP_SPECIFIC_PASSWORD: "wlcl-ubxx-bhmq-kmji"
        XCODE_SCHEME: "Runner"  # שנה אם משתמש ב-Scheme אחר
      flutter: 3.24.0  # גרסת Flutter עדכנית, שנה לפי הצורך
    integrations:
      app_store_connect: GivItAPIKey
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --platform IOS \
            --type IOS_APP_STORE \
            --certificate-type IOS_DISTRIBUTION
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: false  # העלאה ידנית
        release_notes: "Initial release of GivIt - Smart rental platform"
    artifacts:
      - ios/ipa/*.ipa
      - ios/ipa/*.dSYM.zip