workflows:
  ios-app-store:
    name: GivIt iOS App Store Deploy
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - o3
      vars:
        BUNDLE_ID: "${o3.BUNDLE_ID}"
        APPLE_TEAM_ID: "${o3.APPLE_TEAM_ID}"
        ASC_ISSUER_ID: "${o3.ASC_ISSUER_ID}"
        ASC_KEY_ID: "${o3.ASC_KEY_ID}"
        APP_SPECIFIC_PASSWORD: "${o3.APP_SPECIFIC_PASSWORD}"
        XCODE_SCHEME: "App"
        GOOGLE_MAPS_API_KEY: "${o3.GOOGLE_MAPS_API_KEY}"
        GOOGLE_AUTH_SERVER_CLIENT_ID: "${o3.GOOGLE_AUTH_SERVER_CLIENT_ID}"
        CERTIFICATE: "${o3.CERTIFICATE}"
        PRIVATE_KEY_PASSWORD: "${o3.PRIVATE_KEY_PASSWORD}"
      node: 18
    working_directory: frontend
    integrations:
      app_store_connect: GivItAPIKey
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      - name: Build React app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
          echo "VITE_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" > .env
          echo "VITE_GOOGLE_AUTH_SERVER_CLIENT_ID=$GOOGLE_AUTH_SERVER_CLIENT_ID" >> .env
          npx cap copy ios
      - name: Set up code signing
        script: |
          echo "Issuer ID: $ASC_ISSUER_ID, Key ID: $ASC_KEY_ID, Bundle ID: $BUNDLE_ID"
          if [ -z "$ASC_ISSUER_ID" ] || [ -z "$ASC_KEY_ID" ]; then
            echo "Error: Missing Issuer ID or Key ID"
            exit 1
          fi
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --platform IOS \
            --type IOS_APP_STORE \
            || echo "Automatic signing failed, trying manual"
          if [ -n "$CERTIFICATE" ]; then
            echo "$CERTIFICATE" | base64 --decode > ios/certificate.p12
            security create-keychain -p "" build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p "" build.keychain
            security import ios/certificate.p12 -k build.keychain -P "$PRIVATE_KEY_PASSWORD" -T /usr/bin/codesign
            security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          else
            echo "No manual certificate provided, relying on automatic signing"
          fi
      - name: Build IPA
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist ios/ExportOptions.plist
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: false
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/*.dSYM.zip