workflows:
  ios-app-store:
    name: GivIt iOS App Store Deploy
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - o3
      vars:
        BUNDLE_ID: "${o3.BUNDLE_ID}"  # com.orirot.givit
        APPLE_TEAM_ID: "${o3.APPLE_TEAM_ID}"  # 39WVDVZKGE
        ASC_ISSUER_ID: "${o3.ASC_ISSUER_ID}"  # cb979aca-72c6-42a9-8a75-6d6cf1fb264e
        ASC_KEY_ID: "${o3.ASC_KEY_ID}"  # JQ82YP1TDCU0
        APP_SPECIFIC_PASSWORD: "${o3.APP_SPECIFIC_PASSWORD}"  # wlcl-ubxx-bhmq-kmji
        XCODE_SCHEME: "App"  # בדוק שם ה-Scheme
        GOOGLE_MAPS_API_KEY: "${o3.GOOGLE_MAPS_API_KEY}"
        GOOGLE_AUTH_SERVER_CLIENT_ID: "${o3.GOOGLE_AUTH_SERVER_CLIENT_ID}"
      node: 18
    working_directory: frontend  # עבודה מתוך תיקיית frontend
    integrations:
      app_store_connect: GivItAPIKey
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      - name: Build React app
        script: |
          npm run build  # יוצר dist בתוך frontend
      - name: Sync Capacitor
        script: |
          npx cap sync ios
          echo "VITE_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" > .env
          echo "VITE_GOOGLE_AUTH_SERVER_CLIENT_ID=$GOOGLE_AUTH_SERVER_CLIENT_ID" >> .env
          npx cap copy ios
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --platform IOS \
            --type IOS_APP_STORE \
            --certificate-type IOS_DISTRIBUTION
      - name: Build IPA
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist ios/ExportOptions.plist
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: false
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/*.dSYM.zip