workflows:
  ios-app-store:
    name: GivIt iOS App Store Deploy
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - o3  # קבוצת המשתנים שלך
      vars:
        BUNDLE_ID: "${o3.BUNDLE_ID}"  # com.orirot.givit
        APPLE_TEAM_ID: "${o3.APPLE_TEAM_ID}"  # 39WVDVZKGE
        # שאר המשתנים מהקבוצה o3
      flutter: 3.24.0
    integrations:
      app_store_connect: GivItAPIKey  # עכשיו זה אמור להתאים
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --platform IOS \
            --type IOS_APP_STORE \
            --certificate-type IOS_DISTRIBUTION
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    publishing:
      app_store_connect:
        auth: integration  # משתמש באינטגרציה
        submit_to_app_store: false  # ידני
    artifacts:
      - ios/ipa/*.ipa
      - ios/ipa/*.dSYM.zip